In [1]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns


In [10]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks//car_evaluation.csv', header=None)
# index_col=0를 넣으면 index가 없어짐
df.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [11]:
df.columns=['buying', 'maint', 'doors', 'persons','lug_boot', 'safety','class']

In [12]:
df.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [7]:
df.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'], dtype='object')

In [13]:
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

In [17]:
from sklearn.preprocessing import LabelEncoder

# LabelEncoder 생성
le = LabelEncoder()

# 전체 열을 한 번에 변환
df = df.apply(lambda col: le.fit_transform(col))

df.head()

buying  maint  doors  persons  lug_boot  safety  class
0       3      3      0        0         2       1      2
1       3      3      0        0         2       2      2
2       3      3      0        0         2       0      2
3       3      3      0        0         1       1      2
4       3      3      0        0         1       2      2

In [20]:
df['class'].value_counts()

class
2    1210
0     384
1      69
3      65
Name: count, dtype: int64

In [24]:
# 데이터 분할
X = df.drop('class', axis=1).values
y = df['class'].values


In [25]:
X

array([[3, 3, 0, 0, 2, 1],
       [3, 3, 0, 0, 2, 2],
       [3, 3, 0, 0, 2, 0],
       ...,
       [1, 1, 3, 2, 0, 1],
       [1, 1, 3, 2, 0, 2],
       [1, 1, 3, 2, 0, 0]])

In [26]:
y

array([2, 2, 2, ..., 2, 1, 3])

In [27]:
# StandardScaler를 사용해 특성 스케일링
scaler = StandardScaler()
X=scaler.fit_transform(X)

# 훈련데이터와 테스트데이터로 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1382, 6), (346, 6), (1382,), (346,))

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

In [43]:
def plot_confusion_matrix(y_test, y_pred, model_name):
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(6,4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=y_test.unique(), yticklabels=y_test.unique())
    plt.title(f"{model_name} Confusion Maxtrix")
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()

In [46]:
# Decision Tree 모델
dt_model = DecisionTreeClassifier(random_state=42) # Decision Tree 분류기 객체 생성
dt_model.fit(X_train, y_train) # 학습 데이터를 사용해 모델 훈련
dt_pred = dt_model.predict(X_test) # 테스트 데이터에 대한 예측 수행

# 예측 및 정확도 계산
print("Decision Tree 결과:\n", classification_report(y_test, dt_pred)) # Decision Tree 모델의 성능평가
print (confusion_matrix(y_test, dt_pred))

Decision Tree 결과:
               precision    recall  f1-score   support

           0       0.97      0.92      0.94        83
           1       0.62      0.91      0.74        11
           2       1.00      1.00      1.00       235
           3       1.00      0.94      0.97        17

    accuracy                           0.97       346
   macro avg       0.90      0.94      0.91       346
weighted avg       0.98      0.97      0.98       346

[[ 76   6   1   0]
 [  1  10   0   0]
 [  0   0 235   0]
 [  1   0   0  16]]


In [47]:
# Logistic Regression 모델
lr_model = LogisticRegression(max_iter=200) # Logistic Regression 분류기 객체 생성
lr_model.fit(X_train, y_train) # 학습 데이터를 사용해 모델 훈련
lr_pred = lr_model.predict(X_test) # 테스트 데이터에 대한 예측 수행

print("Logistic Regression 결과:\n", classification_report(y_test, dt_pred)) # Logistic Regression 모델의 성능 평가
print (confusion_matrix(y_test, dt_pred))

Logistic Regression 결과:
               precision    recall  f1-score   support

           0       0.97      0.92      0.94        83
           1       0.62      0.91      0.74        11
           2       1.00      1.00      1.00       235
           3       1.00      0.94      0.97        17

    accuracy                           0.97       346
   macro avg       0.90      0.94      0.91       346
weighted avg       0.98      0.97      0.98       346

[[ 76   6   1   0]
 [  1  10   0   0]
 [  0   0 235   0]
 [  1   0   0  16]]


In [51]:
# Support Vector Classifier 모델
svc_model = SVC() # Support Vector Classifier 분류기 객체 생성
svc_model.fit(X_train, y_train) # 학습 데이터를 사용해 모델 훈련
svc_pred = svc_model.predict(X_test) # 테스트 데이터에 대한 예측 수행
print("Support Vector Classifier 결과:\n", classification_report(y_test, dt_pred)) # Support Vector Classifier 모델의 성능 평가
print (confusion_matrix(y_test, dt_pred))

Support Vector Classifier 결과:
               precision    recall  f1-score   support

           0       0.97      0.92      0.94        83
           1       0.62      0.91      0.74        11
           2       1.00      1.00      1.00       235
           3       1.00      0.94      0.97        17

    accuracy                           0.97       346
   macro avg       0.90      0.94      0.91       346
weighted avg       0.98      0.97      0.98       346

[[ 76   6   1   0]
 [  1  10   0   0]
 [  0   0 235   0]
 [  1   0   0  16]]


In [49]:
# Random Forest 모델
rf_model = RandomForestClassifier() # Random Forest 분류기 객체 생성
rf_model.fit(X_train, y_train) # 학습 데이터를 활용해 모델 훈련
rf_pred = rf_model.predict(X_test) # 테스트 데이터에 대한 예측을 수행

print("Rancom Forest 결과:\n", classification_report(y_test, dt_pred)) #Random Forest 모델의 성능 평가(classification_report 출력)
print (confusion_matrix(y_test, dt_pred))

Rancom Forest 결과:
               precision    recall  f1-score   support

           0       0.97      0.92      0.94        83
           1       0.62      0.91      0.74        11
           2       1.00      1.00      1.00       235
           3       1.00      0.94      0.97        17

    accuracy                           0.97       346
   macro avg       0.90      0.94      0.91       346
weighted avg       0.98      0.97      0.98       346

[[ 76   6   1   0]
 [  1  10   0   0]
 [  0   0 235   0]
 [  1   0   0  16]]


In [48]:
# K-Nearest Neighbors 모델
knn_model = KNeighborsClassifier()  # K-Nearest Neighbors 분류기 객체 생성
knn_model.fit(X_train, y_train)  # 학습 데이터를 사용해 모델 훈련
knn_pred = knn_model.predict(X_test)  # 테스트 데이터에 대한 예측 수행

print("K-Nearest Neighbors 결과:\n", classification_report(y_test, dt_pred)) #Random Forest 모델의 성능 평가(classification_report 출력)
print (confusion_matrix(y_test, dt_pred))

K-Nearest Neighbors 결과:
               precision    recall  f1-score   support

           0       0.97      0.92      0.94        83
           1       0.62      0.91      0.74        11
           2       1.00      1.00      1.00       235
           3       1.00      0.94      0.97        17

    accuracy                           0.97       346
   macro avg       0.90      0.94      0.91       346
weighted avg       0.98      0.97      0.98       346

[[ 76   6   1   0]
 [  1  10   0   0]
 [  0   0 235   0]
 [  1   0   0  16]]
